baseURL = 'https://lonlfuller.org/'
languageCode = 'en-us'
title = 'Lon L Fuller'
theme = 'xmin'

[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10

[[menu.main]]
    name = 'Works'
    url = '/works/'
    weight = 10

[[menu.main]]
    name = 'Biography'
    url = '/bio/'
    weight = 20

[[menu.main]]
    name = 'Licensing'
    url = '/licensing/'
    weight = 30


[params]
  footer = "©2026 The Estate of Lon L. Fuller"